import { Inter } from 'next/font/google'
import Link from 'next/link'
import Category from '../components/category'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">

            <body className={inter.className}>
                <header className='category-header'>
                    HEADPHONES
                </header>

                <div>
                    {children}
                </div>

                <Category />
            </body>

        </html>
    )
}
