
import BackBtn from '../components/backBtn'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function ProductsLayout({ children }) {
    return (
        <section>
            <BackBtn />

            <div>
                {children}
            </div>
        </section>
    )
}
